name: Publish Types

# If changes are made to the types/src/** files
# Issue a new release to npm for the types package.
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'types/src/**'
      - 'types/package.json'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Configure SSH with private SSH key
      - name: Attach SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      - name: Configure user info
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install npm dependencies
        run: |
          cd types
          yarn install

      - name: Publish the package
        run: |
          cd types
          yarn publish-types --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Using Github auto-generated token
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Using personal access token
          RELEASE_IT_GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}
