name: Publish Types

# If changes are made to the types/src/** files
# Issue a new release to npm for the types package.
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'types/src/**'
      - 'types/package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: cd types && yarn install

      - name: Configure Github Actions user
        run: |
          git config user.name "${{ vars.RELEASE_IT_NAME }}"
          git config user.email "${{ vars.RELEASE_IT_EMAIL }}"

      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish the package
        run: cd types && yarn publish-types --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}
